weight updation formula =  W(old) + N (learning rate) (y-y^) . x(i)

In [2]:
import numpy as np 

w =np.array([2,2])
x =np.array([2,2]) 

dot= np.dot(w,x) 
dot

np.int64(8)

In [4]:
random_normal = np.random.randn(3) 
random_normal

array([-2.00287353,  0.00344488,  1.36391964])

In [5]:
import pandas as pd 

data ={
    "x1": [0,0,1,1], 
    "x2": [0,1,0,1], 
    "y" : [0,0,0,1]
}
AND = pd.DataFrame(data)

In [6]:
AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [7]:
X = AND.drop("y",axis=1)

In [9]:
y = AND['y']
y.to_frame()

   y
0  0
1  0
2  0
3  1

In [14]:
len(X)

4

In [17]:
bias = -np.ones((len(X),1))

In [18]:
bias = np.c_[X,bias] 
bias

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])

Main Implementauion

In [19]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

In [37]:
class Percepton:
    def __init__(self,eta,epochs):
        self.weights = np.random.randn(3) * 1e-4
        print(f"self.weights {self.weights}")

        self.eta = eta 
        self.epochs = epochs
         

    def activationFunction(self,inputs,weights):
        z= np.dot(inputs,weights)
        return np.where(z>0,1,0)

    def fit(self,X,y):
        self.X =X
        self.y = y

        x_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]

        print(f"X with bias {x_with_bias}") 

        for epoch in range(self.epochs):
            
            print("Epoch ",epoch)
            y_hat = self.activationFunction(x_with_bias,self.weights)

            print(f" Predicted value {y_hat}")
        
            error = self.y - y_hat 
            print(f"Error \n{error} ")
        
                #weight update 
        
            self.weights = self.weights + self.eta * np.dot(x_with_bias.T, error)
        
            print(f"Updated weights \n {self.weights}")
        
            print("############\n")   
     
    def predict(self,X):
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        return self.activationFunction(X_with_bias,self.weights)

In [38]:
import pandas as pd 

data ={
    "x1": [0,0,1,1], 
    "x2": [0,1,0,1], 
    "y" : [0,0,0,1]
}
AND = pd.DataFrame(data) 

X = AND.drop("y",axis=1)
y  = AND['y']
y.to_frame()

   y
0  0
1  0
2  0
3  1

In [39]:
#Model prediction 

model = Percepton(eta=0.5,epochs=10)
model.fit(X,y)

self.weights [ 9.62040625e-05  4.40242990e-05 -9.30424270e-05]
X with bias [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch  0
 Predicted value [1 1 1 1]
Error
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights
 [-0.4999038  -0.49995598  1.49990696]
############

Epoch  1
 Predicted value [0 0 0 0]
Error
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights
 [9.62040625e-05 4.40242990e-05 9.99906958e-01]
############

Epoch  2
 Predicted value [0 0 0 0]
Error
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights
 [0.5000962  0.50004402 0.49990696]
############

Epoch  3
 Predicted value [0 1 1 1]
Error
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated weights
 [9.62040625e-05 4.40242990e-05 1.49990696e+00]
############

Epoch  4
 Predicted value [0 0 0 0]
Error
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated weights
 [0.5000962  0.50004402 0.99990696]
############

Epoch  5
 Predicted value [0 0 0 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights
 [0.5000962  0.50004402 0.99990696]
############

Epoch  6
 Predicted value [0 0 0 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights
 [0.5000962  0.50004402 0.99990696]
############

Epoch  7
 Predicted value [0 0 0 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights
 [0.5000962  0.50004402 0.99990696]
############

Epoch  8
 Predicted value [0 0 0 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights
 [0.5000962  0.50004402 0.99990696]
############

Epoch  9
 Predicted value [0 0 0 1]
Error
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated weights
 [0.5000962  0.50004402 0.99990696]
############