In [1]:
import numpy as np 
import pandas as pd 
import torch 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

         id diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst  Unnamed: 32
0    842302         M        17.99  ...          0.4601                  0.11890          NaN
1    842517         M        20.57  ...          0.2750                  0.08902          NaN
2  84300903         M        19.69  ...          0.3613                  0.08758          NaN
3  84348301         M        11.42  ...          0.6638                  0.17300          NaN
4  84358402         M        20.29  ...          0.2364                  0.07678          NaN

[5 rows x 33 columns]

In [6]:
df.shape

(569, 31)

In [5]:
df.drop(columns=['id','Unnamed: 32'], inplace=True)

# Train test split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [8]:
df['diagnosis'].unique()

array(['M', 'B'], dtype=object)

In [9]:
scaler = StandardScaler() 
X_train = scaler.fit_transform(X_train) 
X_test = scaler.transform(X_test)

In [10]:
encoder = LabelEncoder() 
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [11]:
X_train

array([[ 1.08229858, -0.57346329,  1.02589407, ...,  0.5922489 ,
        -0.07890718, -0.07567769],
       [ 1.1360105 , -0.14114969,  1.1406442 , ...,  0.2697615 ,
         0.21975418, -0.20954797],
       [-0.80044552, -0.09674991, -0.83182854, ..., -0.81241407,
         0.63020499, -0.76809078],
       ...,
       [-0.88808076, -0.51036887, -0.86953216, ..., -0.30395894,
        -0.18235413,  1.86769129],
       [-0.21244136, -0.2346229 , -0.24045556, ..., -0.55012432,
        -0.35254105, -0.98802052],
       [ 0.0928685 ,  0.00840745,  0.07305818, ..., -0.2916737 ,
        -0.69792039, -0.50428758]])

In [12]:
df.head()

  diagnosis  radius_mean  texture_mean  ...  concave points_worst  symmetry_worst  fractal_dimension_worst
0         M        17.99         10.38  ...                0.2654          0.4601                  0.11890
1         M        20.57         17.77  ...                0.1860          0.2750                  0.08902
2         M        19.69         21.25  ...                0.2430          0.3613                  0.08758
3         M        11.42         20.38  ...                0.2575          0.6638                  0.17300
4         M        20.29         14.34  ...                0.1625          0.2364                  0.07678

[5 rows x 31 columns]

In [13]:
X_train

array([[ 1.08229858, -0.57346329,  1.02589407, ...,  0.5922489 ,
        -0.07890718, -0.07567769],
       [ 1.1360105 , -0.14114969,  1.1406442 , ...,  0.2697615 ,
         0.21975418, -0.20954797],
       [-0.80044552, -0.09674991, -0.83182854, ..., -0.81241407,
         0.63020499, -0.76809078],
       ...,
       [-0.88808076, -0.51036887, -0.86953216, ..., -0.30395894,
        -0.18235413,  1.86769129],
       [-0.21244136, -0.2346229 , -0.24045556, ..., -0.55012432,
        -0.35254105, -0.98802052],
       [ 0.0928685 ,  0.00840745,  0.07305818, ..., -0.2916737 ,
        -0.69792039, -0.50428758]])

In [14]:
y_train

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])

In [15]:
type(y_train)

numpy.ndarray

In [17]:
type(y_test)

numpy.ndarray

# Numpy array to tensor

In [18]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [19]:
type(X_test_tensor)

torch.Tensor

# Defining the model

In [21]:
X_test_tensor.shape[1]

30

In [24]:
class MySimpleNN():

    def __init__(self,X):
        self.weights= torch.rand(X_test_tensor.shape[1],1,dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64, requires_grad=True)
         

    def forward(self,X):
        z = torch.matmul(X,self.weights) + self.bias 
        y_pred = torch.sigmoid(z) 
        return y_pred 

    def loss_function(self,y_pred,y):
        #clamp 
        epsilon = 1e-7 
        y_pred = torch.clamp(y_pred,epsilon, 1-epsilon)
        loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1-y_pred)).mean()
        return loss

In [25]:
model = MySimpleNN(X_test_tensor)
model.weights

tensor([[0.3131],
        [0.2602],
        [0.4964],
        [0.4936],
        [0.0308],
        [0.3254],
        [0.1323],
        [0.5109],
        [0.7246],
        [0.3406],
        [0.4548],
        [0.9065],
        [0.8032],
        [0.8752],
        [0.2722],
        [0.3764],
        [0.8257],
        [0.0356],
        [0.3126],
        [0.2810],
        [0.1304],
        [0.9872],
        [0.7000],
        [0.6157],
        [0.0552],
        [0.6095],
        [0.3815],
        [0.2004],
        [0.8734],
        [0.6802]], dtype=torch.float64, requires_grad=True)

In [26]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

# Parameters

In [27]:
learning_rate = 0.1 
epochs = 25

# Training Pipeline

In [29]:
# create model 

model = MySimpleNN(X_train_tensor) 
# define loop 

for epoch in range(epochs):
    # forward pass 
    y_pred = model.forward(X_train_tensor)
    
    #loss calculate 

    loss = model.loss_function(y_pred,y_train_tensor)

    # backward pass
    loss.backward()

    #parameter update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad
    
    #zero gradient 
    model.weights.grad.zero_() 
    model.bias.grad.zero_()

    #print loss in each epoch

    print(f"{epoch+1}, loss ={loss.item()}")

1, loss =3.7684843641782027
2, loss =3.648196100618255
3, loss =3.5184298690844154
4, loss =3.3841335497836313
5, loss =3.2431913793997533
6, loss =3.0979705958757724
7, loss =2.9498396993316094
8, loss =2.7965307503561
9, loss =2.6372440533025205
10, loss =2.476362591338939
11, loss =2.3176172127035146
12, loss =2.1617604035022637
13, loss =2.003307777220615
14, loss =1.8380071145149077
15, loss =1.6796201996255908
16, loss =1.532503351806347
17, loss =1.3984186162776213
18, loss =1.2790404933981685
19, loss =1.1756466257246456
20, loss =1.0887415106850649
21, loss =1.0177650748367488
22, loss =0.9611144956480009
23, loss =0.9165217646788301
24, loss =0.881521426984034
25, loss =0.8538097907310463

# Model evaluation

In [32]:
y_pred = model.forward(X_test_tensor)
print(y_pred)

tensor([[0.1720],
        [0.6396],
        [0.4651],
        [0.2027],
        [0.5591],
        [0.3537],
        [0.4472],
        [0.5504],
        [0.8892],
        [0.6781],
        [0.7779],
        [0.3747],
        [0.9176],
        [0.6687],
        [0.2257],
        [0.1957],
        [0.2623],
        [0.2819],
        [0.3893],
        [0.6741],
        [0.2871],
        [0.1406],
        [0.8331],
        [0.3060],
        [0.8912],
        [0.6187],
        [0.1200],
        [0.2499],
        [0.5945],
        [0.7086],
        [0.8654],
        [0.3252],
        [0.3117],
        [0.1807],
        [0.1951],
        [0.6550],
        [0.9999],
        [0.6279],
        [0.6917],
        [0.2512],
        [0.4763],
        [0.6148],
        [0.9639],
        [0.6920],
        [0.8323],
        [0.3916],
        [0.1111],
        [0.4329],
        [0.8505],
        [0.3104],
        [0.2617],
        [0.7423],
        [0.4846],
        [0.1476],
        [0.2326],
        [0.7987],
        [0.8620],
        [0.1182],
        [0.3084],
        [0.6660],
        [0.3185],
        [0.7275],
        [0.1628],
        [0.6209],
        [0.4594],
        [0.3771],
        [0.7527],
        [0.2646],
        [0.4609],
        [0.5032],
        [0.9950],
        [0.2405],
        [0.6536],
        [0.5929],
        [0.4681],
        [0.9374],
        [0.6313],
        [0.9689],
        [0.3412],
        [0.1833],
        [0.6434],
        [0.8245],
        [0.4357],
        [0.4021],
        [0.2468],
        [0.5261],
        [0.9889],
        [0.2347],
        [0.4184],
        [0.7403],
        [0.1932],
        [0.3893],
        [0.1265],
        [0.7405],
        [0.8719],
        [0.6443],
        [0.2488],
        [0.8755],
        [0.4167],
        [0.3995],
        [0.1399],
        [0.2096],
        [0.8125],
        [0.2745],
        [0.9474],
        [0.4888],
        [0.4723],
        [0.5874],
        [0.2873],
        [0.5187],
        [0.2061],
        [0.5509],
        [0.1321],
        [0.3704]], dtype=torch.float64, grad_fn=<SigmoidBackward0>)

In [42]:
with torch.no_grad():
    y_pred = (y_pred > 0.9).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
    print(f"accuracy = {accuracy.item()}")

accuracy = 0.6131117343902588